# Generated by Django 4.1 on 2022-08-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authatication', '0003_rename_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
